spring:
  datasource:
    # 사용할 데이터베이스 정보 입력
    url: jdbc:tibero:thin:@192.168.0.58:18229:tibero #주소 값
    username: syscat                                   # ID
    password: syscat                                   # PW
    driver-class-name: com.tmax.tibero.jdbc.TbDriver  # Driver

  jpa:
    hibernate:
      # ddl-auto 값 설정 ( default : none / create, create-drop, update, none, validate )
      ddl-auto: none
    #      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true  # 쿼리문이 나가는것을 보여주는 명령어
        default_batch_fetch_size: 100 # 쿼리문을 n개 만큼 모아서 한꺼번에 날려주는 명령어
        dialect: org.hibernate.dialect.Oracle10gDialect
    open-in-view: false

#  mvc:
#    view:
#      prefix: /jsp/
#      suffix: .jsp
#    static-path-pattern: /**
logging:
  level:
    com.example.demo: DEBUG
